import proPic from "./Assets/oneness.jpg";
import busPic from "./Assets/pic56.jpg";

export const bookingData = [
  {
    name: "Jan",
    Booking: 2000,
  },
  {
    name: "Feb",
    Booking: 3000,
  },
  {
    name: "Mar",
    Booking: 1750,
  },
  {
    name: "Apr",
    Booking: 2780,
  },
  {
    name: "May",
    Booking: 1890,
  },
  {
    name: "Jun",
    Booking: 2390,
  },
  {
    name: "Jul",
    Booking: 3490,
  },
  {
    name: "Aug",
    Booking: 2500,
  },
  {
    name: "Sep",
    Booking: 3000,
  },
  {
    name: "Oct",
    Booking: 1700,
  },
  {
    name: "Nov",
    Booking: 2900,
  },
  {
    name: "Dec",
    Booking: 4000,
  },
];

export const packagerRows = [
  {
    id: 1,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 2,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 3,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 4,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 5,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 6,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 7,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 8,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 9,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
  {
    id: 10,
    pic: proPic,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    status: "Active",
  },
];

export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 2,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 3,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 4,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 5,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 6,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 7,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 8,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 9,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
  {
    id: 10,
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    profession: "Student",
  },
];
export const packageData = [
  {
    name: "Wayanad",
    booking: 10,
    Bookings: 15,
  },
  {
    name: "Munnar",
    booking: 10,
    Bookings: 25,
  },
  {
    name: "Vagamon",
    booking: 10,
    Bookings: 10,
  },
  {
    name: "Kanyakumari",
    booking: 10,
    Bookings: 5,
  },
  {
    name: "Ooty",
    booking: 10,
    Bookings: 17,
  },
  {
    name: "Kodaikanal",
    booking: 10,
    Bookings: 12,
  },
  {
    name: "Velamkanni",
    booking: 10,
    Bookings: 8,
  },
  {
    name: "Uduppi",
    booking: 10,
    Bookings: 9,
  },
  {
    name: "Malpe",
    booking: 10,
    Bookings: 15,
  },
  {
    name: "Coorg",
    booking: 10,
    Bookings: 20,
  },
  {
    name: "Goa",
    booking: 10,
    Bookings: 25,
  },
  {
    name: "Dandeli",
    booking: 10,
    Bookings: 13,
  },
];
export const packageRows = [
  {
    id: 1,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 2,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 3,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 4,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 5,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 6,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 7,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 8,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 9,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
  {
    id: 10,
    username: "Goa",
    rate: "2000",
    noofdays: "3",
    description:
      "The package includes the food and accomodation in 4 star hotels.",
  },
];
export const districtData = [
  { id: 1, districtname: "Idukki" },
  { id: 2, districtname: "Idukki" },
  { id: 3, districtname: "Idukki" },
  { id: 4, districtname: "Idukki" },
  { id: 5, districtname: "Idukki" },
  { id: 6, districtname: "Idukki" },
  { id: 7, districtname: "Idukki" },
  { id: 8, districtname: "Idukki" },
  { id: 9, districtname: "Idukki" },
  { id: 10, districtname: "Idukki" },
];
export const stateData = [
  { id: 1, statename: "Kerala" },
  { id: 2, statename: "Kerala" },
  { id: 3, statename: "Kerala" },
  { id: 4, statename: "Kerala" },
  { id: 5, statename: "Kerala" },
  { id: 6, statename: "Kerala" },
  { id: 7, statename: "Kerala" },
  { id: 8, statename: "Kerala" },
  { id: 9, statename: "Kerala" },
  { id: 10, statename: "Kerala" },
];
export const locationData = [
  {
    id: 1,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 2,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 3,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 4,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 5,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 6,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 7,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 8,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 9,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
  {
    id: 10,
    locationname: "Thodupuzha",
    districtname: "Idukki",
    locationpincode: "685588",
  },
];
export const transactionData = [
  {
    id: 1,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 2,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 3,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 4,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 5,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 6,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 7,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 8,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 9,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 10,
    username: "Micheal",
    packagername: "Oneness Travels",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
];
export const busModelData = [
  {
    id: 1,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 2,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 3,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 4,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 5,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 6,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 7,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 8,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 9,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
  {
    id: 10,
    busmodelname: "Zedone",
    busmodelfeatures: "AC/Pushback",
  },
];
export const feedbackData = [
  {
    id: 1,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 2,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 3,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 4,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 5,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 6,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 7,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 8,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 9,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
  {
    id: 10,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
    content: "Feedback C",
  },
];
export const complaintData = [
  {
    id: 1,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 2,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 3,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 4,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 5,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 6,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 7,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 8,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 9,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 10,
    cusername: "Mikhael",
    cpackagername: "Oneness Travels",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
];
export const packagerapprovalRows = [
  {
    id: 1,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 2,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 3,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 4,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 5,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 6,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 7,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 8,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 9,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
  {
    id: 10,
    pic: proPic,
    packagerapprovalname: "Oneness Travels",
    username: "Jon Snow",
    email: "jonsnow@gmail.com",
    contact: "9988776655",
    location: "Thodupuzha",
    dateofrequest: "19-03-2022",
  },
];
export const ratingData = [
  {
    id: 1,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 2,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 3,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 4,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 5,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 6,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 7,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 8,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 9,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
  {
    id: 10,
    username: "Mikhael",
    packagername: "Oneness Travels",
    date: "18-03-2022",
  },
];
export const bookingTableData = [
  {
    id: 1,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 2,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 3,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 4,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 5,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 6,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 7,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 8,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 9,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
  {
    id: 10,
    username: "Micheal",
    packagername: "Oneness Travels",
    busname: "KingBull",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    status: "Success",
  },
];

export const busData = [
  {
    id: 1,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 2,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 3,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 4,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 5,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 6,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 7,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 8,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 9,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
  {
    id: 10,
    pic: busPic,
    busname: "Dhashavathar",
    buscapacity: "49 Seats",
    busmodel: "Zedone",
    busfeatures: "AC Pushback",
    busyear: "2019",
  },
];

export const packagerReportBookingData = [
  {
    id: 1,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 2,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 3,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 4,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 5,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 6,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 7,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 8,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 9,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
  {
    id: 10,
    name: "Micheal",
    packagename: "Goa",
    bookingdate: "16-03-2022",
    tripdate: "04-04-2022",
    place: "Thodupuzha",
    noofpeople: "45",
    bus: "KingBull",
    status: "Success",
  },
];

export const packagerReportTransactionData = [
  {
    id: 1,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 2,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 3,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 4,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 5,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 6,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 7,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 8,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 9,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
  {
    id: 10,
    username: "Micheal",
    packagename: "Goa",
    date: "16-03-2022",
    amount: "10000",
    status: "Success",
  },
];

export const packagerReportTransactionChartData = [
  {
    name: "Jan",
    Transaction: 30000,
  },
  {
    name: "Feb",
    Transaction: 35000,
  },
  {
    name: "Mar",
    Transaction: 29500,
  },
  {
    name: "Apr",
    Transaction: 20800,
  },
  {
    name: "May",
    Transaction: 18900,
  },
  {
    name: "Jun",
    Transaction: 23900,
  },
  {
    name: "Jul",
    Transaction: 24900,
  },
  {
    name: "Aug",
    Transaction: 25000,
  },
  {
    name: "Sep",
    Transaction: 19000,
  },
  {
    name: "Oct",
    Transaction: 20000,
  },
  {
    name: "Nov",
    Transaction: 29000,
  },
  {
    name: "Dec",
    Transaction: 35000,
  },
];

export const packagerNotificationsComplaintData = [
  {
    id: 1,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 2,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 3,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 4,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 5,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 6,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 7,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 8,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 9,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
  {
    id: 10,
    cusername: "Mikhael",
    packagename: "Goa",
    complaintdate: "15-03-2022",
    replydate: "18-03-2022",
    complaintstatus: "Resolved",
  },
];

export const packagerNotificationsFeedbackData = [
  {
    id: 1,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 2,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 3,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 4,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 5,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 6,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 7,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 8,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 9,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
  {
    id: 10,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
    content: "Good Travelling Facility and Nice Food and Accomodation",
  },
];

export const packagerRatingViewData = [
  {
    id: 1,
    username: "Mikhael",
    packagename: "Goa",
    date: "18-03-2022",
  },
  {
    id: 2,
    username: "Mikhael",
    packagename: "Wayanad",
    date: "18-03-2022",
  },
  {
    id: 3,
    username: "Mikhael",
    packagename: "Coorg",
    date: "18-03-2022",
  },
  {
    id: 4,
    username: "Mikhael",
    packagename: "Malpe",
    date: "18-03-2022",
  },
  {
    id: 5,
    username: "Mikhael",
    packagename: "Dandeli",
    date: "18-03-2022",
  },
  {
    id: 6,
    username: "Mikhael",
    packagename: "Munnar",
    date: "18-03-2022",
  },
  {
    id: 7,
    username: "Mikhael",
    packagename: "vagamon",
    date: "18-03-2022",
  },
  {
    id: 8,
    username: "Mikhael",
    packagename: "Chikkamagaluru",
    date: "18-03-2022",
  },
  {
    id: 9,
    username: "Mikhael",
    packagename: "Ooty",
    date: "18-03-2022",
  },
  {
    id: 10,
    username: "Mikhael",
    packagename: "Kodaikanal",
    date: "18-03-2022",
  },
];


export const userMyBookingsData = [
  {
    id: 1,
    packagername: "Oneness Travels",
    packagename: "Wayanad",
    bookingdate: "18-03-2022",
    tripdate: "02-04-2022",
    paymentstatus: "Success",
    tripstatus:"Not Completed",
  },
];
